apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-metallb
  namespace: flux-system
spec:
  interval: 1m
  path: ./cluster/infra/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    