apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-metallb-crs
  namespace: flux-system
spec:
  interval: 1m
  path: ./cluster/infra/metallb-crs
  prune: true
  dependsOn:
    - name: infra-metallb
  sourceRef:
    kind: GitRepository
    name: flux-system
    