apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
type: Opaque
data:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:0LiDiVHtyjACkvEXVtIIaw==,iv:sbDuv+uATqWQBNdr69tFwZixo7kyzKoZD1iMI0ikeuM=,tag:wK052yQQ+QoG+nLV3R7u/Q==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:jJRBvO0VRvG5ZdUX,iv:EMz03z68ioHPsyaQOaraQ5QJJcXrQ0XN3bz+JouFmGM=,tag:e4aK7VmNC5N8zPziTUymqw==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:oXozOd1V4QU27WNL,iv:+soxiPh8F3iRFrzl4V/IAsa2uF5h91bl57/QMiNLjxQ=,tag:eu4iiDZ8LKu1v67zElPffw==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:ZY9G4CzgXGBWgNKKjrOeLVM2KqA=,iv:Cn43TKOHdtAVb+DHjyaDBWMLJdPAdqETQaXE5KSXIjw=,tag:KyVb967eynhSpCbHhmYdGw==,type:str]
sops:
    age:
        - recipient: age1knfwtj6s2kagqts3907e9dk9z94hh2pax24azdxlasuf3etqcsqssuug9f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TXFwZ2w5bkxoQjU1alVr
            em1sRmJNc240VVFXUFJIZTVTQjB1MHFGdlhFCmY1c0VacXEraEhRWVl2cFJWbjFz
            alBqRDg5dW5jWjdrVkxZcHVNRlhuYjQKLS0tIE0zaXJWN1cySGZlU0k5dVJtYmRY
            ODBiWWxyUFVLWUk3K3dTcHpjQWdNUlUKhXldHtmuTCX5cMdfluL22FMXdkVU2lpQ
            Fx8VP1VDKjahC2QmfUmfHEOe598izW+v5PimS//TJtl4WDm2B6mAdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-18T16:44:04Z"
    mac: ENC[AES256_GCM,data:JCY0LWYX4092Rthq6IJZsJfg2IB1NM4g5JkmI6kMU08tE+M5vz+bgtOjKvjEMR66ut/GbZoES8GCOAwrM6WbuL0pq5BQIwJ12hPFpIuimcMZAEEpuwYR0ISvXjsgS28XzR8AZhYi5bJA+JwIcHd7Od/lZKGuFcu8fK3ipu7aXQ0=,iv:C0rZICZNtoVMQbtOPSOp635C7h21Qhd5Q3y+neR65Kg=,tag:qxK2Mf0P7kEdBMMGMAT7jg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
